### ISSUE TITLE
SSLError in aliyun and qcloud

### ISSUE THREAD

**Issue by lizhemingi** [wong2/pmm#2]
I use pip(2.7 and 3.5) install successfully in my aliyun ECS and qcloud CVM, but failed when I run pmm command.

>Traceback (most recent call last):
  File "/usr/local/bin/pmm", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pmm/cli.py", line 19, in main
    mirrors = get_mirrors_data()
  File "/usr/local/lib/python2.7/dist-packages/pmm/data.py", line 21, in get_mirrors_data
    mirrors_data = fetch_mirrors_data()
  File "/usr/local/lib/python2.7/dist-packages/pmm/data.py", line 15, in fetch_mirrors_data
    r = requests.get(api_url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)
requests.exceptions.SSLError: hostname 'www.pypi-mirrors.org' doesn't match 'blog.alipay-inc.xyz'

Maybe we can add 'verify=False' in fetch_mirrors_data() to avoid ssl check. Or do you have any better idea?

**Comment by wong2** [comment]
I've made a new release with `verify=False`, please have another try.

**Comment by lizhemingi** [comment]
Yeah, it works.  Nice work bro. 

小黄鸡很棒啊，我不怎么玩人人都知道这个东西。

**Comment by wong2** [comment]
Haha thanks
